name: ci
on:
  push:
    branches:
      - main

jobs:
  deploy-cryptoscool:
    runs-on: ubuntu-latest

    steps:
      - name: git pull
        uses: fifsky/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          pass: ${{ secrets.SSH_PASS }}
          command: |
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
            chmod +x ~/.nvm/nvm.sh
            source ~/.bashrc
            cd /var/www/www-root/data/www/cryptoscool.ru/mongotest
            git pull
      - name: install packages
        uses: appleboy/ssh-action@v1.0.2
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASS }}
          script: |
            echo "start installing"
            apt update
            node -e "console.log('Running Node.js ' + process.version)"
            cd /var/www/www-root/data/www/cryptoscool.ru/mongotest
            node -e "console.log('Running Node.js ' + process.version)"
            nvm use v16
            node -e "console.log('Running Node.js ' + process.version)"
            npm install && npm run build
            pm2 restart cryptoscool
